version: '3.7'
services:
  notes:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "5000:5000"
    container_name: notes
    restart: always
    environment:
        - ASPNETCORE_URLS=http://+:5000
    volumes:
        - /docker-volumes/NotesPages/Notes:/app/Pages/
    networks:
        - nginx_reverse_proxy

networks:
    nginx_reverse_proxy:
        external:
            name: nginx_reverse_proxy