version: '3.4'
services:
  notes:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: notes
    restart: always
    volumes:
        - /docker-volumes/NotesPages/Notes:/app/publish/Pages/
    networks:
        - nginx_reverse_proxy

networks:
    nginx_reverse_proxy:
        external:
            name: nginx_reverse_proxy